mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
package com.sponsorflow.agents.direction
import android.util.Log
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
data class CommandHandlerPayload(
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    val rawCommand: String
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
) : AgentPayload
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
data class CommandHandlerData(
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    val parsedCommand: String,
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    val parsedArgs: Map<String, String>,
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    val proposedAction: ActionIntent?
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
) : AgentResponseData
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
/**
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
 * [ACTUALIZACIÓN 2026 - MIGRADO A TIPADO ESTRICTO E INYECCIÓN]
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
 * COMMAND HANDLER AGENT (La Terminal de Intenciones - Nivel Dios)
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
 * 
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
 * Intercepta comandos crudos estilo CLI (> publish --platform ig) generados 
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
 * por el dueño del dispositivo o por subsistemas internos (como el RetargetingAgent).
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
 * Traduce estos comandos de alto nivel a instrucciones biomecánicas para la Mano Fantasma.
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
 */
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
class CommandHandlerAgent @Inject constructor() : TypedSponsorflowAgent<CommandHandlerPayload, CommandHandlerData>() {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    private const val TAG = "NEXUS_CommandHandler"
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    override val agentName: String = "CommandHandlerAgent"
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    override val squadron: SquadType = SquadType.DIRECTION
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    override val capabilities: List<String> = listOf("cli_parsing", "tactical_orchestration")
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    override fun mapLegacyTaskToPayload(task: AgentTask): CommandHandlerPayload {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        return CommandHandlerPayload(rawCommand = task.message.text.trim())
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    }
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    override fun extractLegacyProposedAction(data: CommandHandlerData): ActionIntent? {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        return data.proposedAction
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    }
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    override suspend fun executeTypedInternal(task: SwarmTask<CommandHandlerPayload>): SwarmResult<CommandHandlerData, SwarmError> {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        val rawCommand = task.payload.rawCommand
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        Log.i(TAG, "💻 [TERMINAL DE INTENCIONES] Procesando directiva: \$rawCommand")
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        // PARSER DE FUERZA BRUTA (Cero IA, split matemático)
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        // Ejemplo esperado: > publish --platform ig --caption "Oferta!" --user "valeria_99"
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        try {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            val parts = rawCommand.split(" ")
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            if (parts.size < 2) return SwarmResult.Failure(SwarmError.InternalException("Falta baseCommand en Terminal"))
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            val baseCommand = parts[1] // Ignoramos el ">" en index 0
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            val args = mutableMapOf<String, String>()
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            var currentKey = ""
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            var currentValue = StringBuilder()
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            for (i in 2 until parts.size) {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                val token = parts[i]
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                if (token.startsWith("--")) {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                    if (currentKey.isNotEmpty()) {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                        args[currentKey] = currentValue.toString().trim().removeSurrounding("\"")
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                        currentValue.clear()
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                    }
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                    currentKey = token.removePrefix("--")
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                } else {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                    currentValue.append("\$token ")
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                }
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            }
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            if (currentKey.isNotEmpty()) {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                args[currentKey] = currentValue.toString().trim().removeSurrounding("\"")
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            }
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            Log.d(TAG, "Instrucciones Parseadas: Comando=[\$baseCommand], Argumentos=\$args")
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            // ENSAMBLAJE DE LA MISIÓN PARA LA MANO FANTASMA (AccessibilityMimic)
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            val actionType = when (baseCommand) {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                "publish" -> "MIMIC_PUBLISH_STORY"
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                "reply" -> "MIMIC_REPLY_COMMENT"
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                "dm" -> "MIMIC_SEND_DM"
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                else -> "UNKNOWN_COMMAND"
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            }
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            if (actionType == "UNKNOWN_COMMAND") {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                Log.w(TAG, "⚠️ Comando de terminal no soportado: \$baseCommand")
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                return SwarmResult.Failure(SwarmError.InternalException("Comando desconocido: \$baseCommand"))
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            }
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            // Encapsulamos todas las variables en un Serializado para enviárselo 
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            // al Accessibility Mimic mediante un ActionIntent
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            val payloadData = args.map { "\${it.key}:::\${it.value}" }.joinToString("|||")
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            return SwarmResult.Success(
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                confidenceScore = 1.0,
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                data = CommandHandlerData(
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                    parsedCommand = baseCommand, 
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                    parsedArgs = args,
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                    proposedAction = ActionIntent(type = actionType, payload = payloadData)
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
                )
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            )
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject

mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        } catch (e: Exception) {
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            Log.e(TAG, "💥 Error de sintaxis en la Terminal de Intenciones: \${e.message}")
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
            return SwarmResult.Failure(SwarmError.InternalException("Error parseando comando: \${e.message}"))
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
        }
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
    }
mport com.sponsorflow.agents.TypedSponsorflowAgent
mport com.sponsorflow.models.ActionIntent
mport com.sponsorflow.models.AgentPayload
mport com.sponsorflow.models.AgentResponseData
mport com.sponsorflow.models.AgentTask
mport com.sponsorflow.models.SquadType
mport com.sponsorflow.models.SwarmError
mport com.sponsorflow.models.SwarmResult
mport com.sponsorflow.models.SwarmTask
mport javax.inject.Inject
}
